Repository neuro-inc/apolo-cli, pull requests merged in 2020-01, with the labels that each got.

#1274 Adjust NAME column of `neuro ps` so that grep by name works.
  CHANGELOG.D/1189.feature
  neuromation/cli/formatters/jobs.py
Labels: CLIents, platform

#1276 Add options --exclude and --include in `neuro storage cp`.
  CHANGELOG.D/1182.feature
  README.md
  neuromation/api/file_filter.py
  neuromation/api/storage.py
  neuromation/cli/storage.py
  tests/api/test_file_filter.py
  tests/e2e/test_e2e_storage.py
Labels: CLIents, enhancement, platform

#1277 `neuro kill` exits now non-zero code if it failed to kill any job in the list
  CHANGELOG.D/1272.bug
  neuromation/cli/job.py
  tests/e2e/test_e2e_jobs.py
Labels: CLIents, platform

#1275 Add neuro admin add-quota / set-quota commands
  CHANGELOG.D/1142.feature
  README.md
  neuromation/api/admin.py
  neuromation/cli/admin.py
  neuromation/cli/config.py
  neuromation/cli/formatters/config.py
  tests/api/test_admin.py
  tests/cli/test_formatters.py
Labels: CLIents, platform

#1296 Allow blank lines and comments in --env-file.
  CHANGELOG.D/1208.feature
  neuromation/cli/job.py
  tests/cli/test_job.py
Labels: enhancement
